Repository topcoder-platform/community-app, pull requests merged in 2019-07, with the labels that each got.

#2943 issue 2754 fix
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Accessibility, Code Review Passed

#2938 MSFT-33
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersSwitch.jsx.snap
  src/shared/components/challenge-listing/Filters/FiltersSwitch/index.jsx
Labels: Accessibility, Code Review Passed

#2976 Fix for Issue #2910 - Don't read out title when menu open
  src/shared/components/challenge-detail/Header/index.jsx
  src/shared/containers/challenge-detail/index.jsx
Labels: Accessibility, Code Review Passed

#2953 issue 2907 done
  src/shared/components/TopcoderHeader/Auth/style.scss
Labels: Accessibility, Code Review Passed

#2950 issue 2886 fix
  __tests__/shared/components/ProfilePage/Header/__snapshots__/index.jsx.snap
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  __tests__/shared/components/TopcoderHeader/mobile/__snapshots__/UserMenu.jsx.snap
  __tests__/shared/components/__snapshots__/Handle.jsx.snap
  src/shared/utils/tc.js
Labels: Accessibility, Code Review Passed

#2970 MSFT-16
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Accessibility, Code Review Passed

#2981 Fix for Issue #2739 - Add lang attribute
  __tests__/shared/__snapshots__/index.jsx.snap
  src/shared/app.jsx
Labels: Code Review Passed, Merged for QA

#2978 Fix for Issue #2887 MSFT-229
  src/shared/components/challenge-listing/ChallengeCard/style.scss
Labels: Accessibility, Merged for QA

#2968 2885 fix
  src/shared/components/ProfilePage/Header/styles.scss
Labels: Accessibility, Code Review Passed

#2975 Issue 2789 fix
  __tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
  src/shared/components/TopcoderFooter/index.jsx
Labels: Accessibility, Merged for QA

#2971 MSFT-78
  __tests__/shared/components/ProfilePage/Skill/__snapshots__/index.jsx.snap
  src/shared/components/ProfilePage/Skill/index.jsx
Labels: Accessibility, Code Review Passed

#2962 MSFT-37
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeFilters.jsx.snap
  src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
Labels: Accessibility, Code Review Passed

#2960 MSFT-214
  src/shared/components/challenge-listing/Filters/_fix_DateInput__input.css
Labels: Accessibility, Merged for QA

#2940 MSFT-123
  src/assets/images/icon-arrow-down.svg
  src/assets/images/icon-arrow-up.svg
Labels: Accessibility, Merged for QA

#2958 Fix for Issue #2819 - Eligible event
  src/assets/images/tco19_logo_black.svg
Labels: Accessibility, Merged for QA

#2917 MSFT-25
  src/shared/components/challenge-listing/Listing/Bucket/style.scss
Labels: Accessibility, Merged for QA

#2942 MSFT-236-Issue#2893 - proper name read out when hover on join or login button
  __tests__/shared/components/TopcoderHeader/__snapshots__/Auth.jsx.snap
  src/shared/components/TopcoderHeader/Auth/index.jsx
Labels: Accessibility, Merged for QA

#2956 MSFT-200 #2865
  __tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
  src/shared/components/TopcoderFooter/index.jsx
Labels: Accessibility, Merged for QA

#2957 issue 2743 fix
  src/shared/components/challenge-listing/Filters/FiltersCardsType/style.scss
Labels: Accessibility, Code Review Passed

#2931 MSFT-153
  src/shared/components/SubmissionPage/FilestackFilePicker/styles.scss
Labels: Accessibility, Code Review Passed, no react-ui changes

#2918 MSFT-29
  src/shared/components/TopcoderFooter/style.scss
Labels: Accessibility, Merged for QA, no react-ui changes

#2919 MSFT-28
  src/shared/components/challenge-listing/Sidebar/BucketSelector/style.scss
Labels: Accessibility, Code Review Passed, Merged for QA, no react-ui changes

#2920 MSFT-24
  src/shared/components/challenge-listing/ChallengeCard/Status/style.scss
Labels: Accessibility, Merged for QA, no react-ui changes

#2922 MSFT-26
  src/shared/components/challenge-listing/Sidebar/BucketSelector/Bucket/style.scss
Labels: Accessibility, Code Review Passed, no react-ui changes

#2932 MSFT-30
  src/shared/components/TopcoderFooter/style.scss
Labels: Accessibility, Code Review Passed, no react-ui changes

#2934 MSFT 178 issue#2850 - added border on view more challenges button focus state
  src/shared/components/challenge-listing/Listing/Bucket/style.scss
Labels: Accessibility, Code Review Passed, Merged for QA

#2935 MSFT-86
  src/shared/components/challenge-detail/Specification/SideBar/styles.scss
Labels: Accessibility, Code Review Passed, react-ui changes

#2937 MSFT-17 & MSFT-35
  src/shared/components/challenge-listing/Sidebar/BucketSelector/Bucket/style.scss
Labels: Accessibility, Merged for QA

#2945 issue 2835 fix
  src/shared/components/challenge-listing/ChallengeCard/NumRegistrants/index.jsx
Labels: Accessibility, Merged for QA

#2965 issue 2786 fix
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersPanel.jsx.snap
  src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#2977 Fix for Issue #2836 - Read submenu link on hover
  __tests__/shared/components/TopcoderHeader/desktop/SubMenu/Item.jsx
  __tests__/shared/components/TopcoderHeader/desktop/SubMenu/__snapshots__/Item.jsx.snap
  src/shared/components/TopcoderHeader/desktop/SubMenu/Item/index.jsx
Labels: Accessibility, Code Review Passed

#2990 issue fix
  src/shared/components/challenge-listing/ChallengeCard/index.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#2994 MSFT-16 Mobile Fix
  src/shared/components/TopcoderHeader/mobile/Header/index.jsx
Labels: Accessibility, Merged for QA

#2997 2802
  src/shared/components/SwitchWithLabel/index.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#2999 changes for #2844
  src/shared/components/SubmissionPage/Submit/styles.scss
Labels: Accessibility, Code Review Passed, Merged for QA

#3000 changes for #2842
  src/shared/components/SubmissionPage/Header/styles.scss
Labels: Accessibility, Code Review Passed, Merged for QA

#3004 changes for #2841
  src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#3006 MSFT-233 Issue#2891
  src/shared/components/challenge-detail/Specification/SideBar/index.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#3007 Change improper role attr of drag drop submission form.
  src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx
Labels: Accessibility, Merged for QA

#3056 MSFT 122 Issue#2820 - fixed improper heading level structure
  src/shared/components/challenge-detail/Header/index.jsx
  src/shared/components/challenge-detail/Specification/SideBar/index.jsx
  src/shared/components/challenge-detail/Specification/SideBar/styles.scss
Labels: Accessibility, Merged for QA

#3057 MSFT 127 issue#2825 - added proper labels for links in sharing
  src/shared/components/challenge-detail/Specification/SideBar/ShareSocial.jsx
Labels: Accessibility, Merged for QA

#2992 2864
  __tests__/shared/components/ProfilePage/__snapshots__/index.jsx.snap
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  __tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeSearchBar.jsx.snap
  src/shared/components/Dashboard/index.jsx
  src/shared/components/ProfilePage/Stats/index.jsx
  src/shared/components/ProfilePage/index.jsx
  src/shared/components/ReviewOpportunityDetailsPage/index.jsx
  src/shared/components/SubmissionPage/index.jsx
  src/shared/components/TopcoderFooter/index.jsx
  src/shared/components/TopcoderHeader/index.jsx
  src/shared/components/challenge-listing/Filters/ChallengeSearchBar/index.jsx
  src/shared/containers/SubmissionManagement/index.jsx
  src/shared/containers/challenge-detail/index.jsx
  src/shared/containers/challenge-listing/Listing/index.jsx
Labels: Accessibility, Merged for QA

#2921 MSFT-18
  src/shared/components/TopcoderHeader/style.scss
Labels: Accessibility, Merged for QA

#2936 issue 2837 fix
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#3121 Fix for Issue #2832 Deadlines section
  src/shared/components/challenge-detail/Header/DeadlinesPanel/index.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#3002 Topcoder open logo add title and aria-label.
  src/assets/images/tco19_logo_black.svg
Labels: Accessibility, Code Review Passed, Merged for QA

#3119 Issue 2810 fix
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/DateRangePicker.jsx.snap
  src/shared/components/challenge-listing/Filters/DateRangePicker.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#2923 MSFT-22
  src/shared/components/TrackIcon/style.scss
Labels: Accessibility, Merged for QA

#3145 MSFT-107
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/DateRangePicker.jsx.snap
  src/shared/components/challenge-listing/Filters/DateRangePicker.jsx
Labels: Accessibility, Merged for QA

#3144 MSFT-149
  src/shared/components/SubmissionPage/Submit/index.jsx
  src/shared/components/SubmissionPage/Submit/styles.scss
Labels: Accessibility, Merged for QA

#3143 MSFT-148
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersPanel.jsx.snap
  src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
Labels: Accessibility, Merged for QA

#2933 Issue 2873 fix
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Accessibility, Merged for QA

#2966 community app issue-2853
  src/client/index.jsx
Labels: Accessibility, Code Review Passed

#2947 MSFT-124
  src/shared/components/challenge-detail/Header/TabSelector/index.jsx
Labels: Accessibility, Code Review Passed

#2998 fix for #2846
  src/shared/components/SubmissionPage/Submit/styles.scss
Labels: Accessibility, Code Review Passed

#3005 changes for #2799
  src/shared/containers/SubmissionPage.jsx
Labels: Accessibility, Merged for QA

#3114 Fix #2911 [MSFT-264] Keyboard access tab operational missing
  src/client/styles.scss
Labels: Accessibility, Merged for QA

#3117 Fix #2824 {MSFT-126} Sample challenge page: There is a Question mark …
  src/shared/components/challenge-detail/Specification/SideBar/index.jsx
Labels: Accessibility, Merged for QA

#3149 Issue 2907 fix
  src/shared/components/TopcoderHeader/Auth/style.scss
Labels: Accessibility, Merged for QA

#3138 Issue 3099 fix
  __tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
  src/shared/components/TopcoderFooter/icons/facebook.svg
  src/shared/components/TopcoderFooter/icons/google_plus.svg
  src/shared/components/TopcoderFooter/icons/instagram.svg
  src/shared/components/TopcoderFooter/icons/linkedin.svg
  src/shared/components/TopcoderFooter/icons/twitter.svg
Labels: Code Review Passed, Contentful, On hold

#3137 Issue 3136 fix
  src/shared/components/Contentful/ContentBlock/themes/general.scss
Labels: Code Review Passed, Contentful, On hold

#3135 Issue 2874 fix
  src/shared/components/SortingSelectBar/style.scss
Labels: Code Review Passed, Contentful

#3134 Issue 3092 fix
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
  src/shared/components/TopcoderHeader/style.scss
Labels: Code Review Passed, Contentful, On hold

#3133 Issue 3089 fix
  src/shared/components/Contentful/Viewport/Viewport.jsx
Labels: Code Review Passed, Contentful

#3131 Issue 3106 fix
  src/shared/utils/tc.js
Labels: Code Review Passed, Contentful, On hold

#2969 Issue 2892 fix
  __tests__/shared/components/challenge-listing/Sidebar/__snapshots__/Footer.jsx.snap
  src/shared/components/challenge-listing/Sidebar/Footer/index.jsx
  src/shared/components/challenge-listing/Sidebar/Footer/style.scss
Labels: Accessibility, Merged for QA

#3128 Update label for form
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Code Review Passed, Contentful, On hold

#3153 Issue 3096 fix
  src/shared/components/Contentful/ContentBlock/themes/general.scss
Labels: Contentful, Merged for QA

#3161 MSFT-122-Issue#2820 - fixed heading level
  src/shared/components/challenge-detail/Specification/SideBar/EligibleEvents/index.jsx
Labels: Accessibility, Merged for QA

#3164 MSFT-186
  src/assets/images/social/icon_facebook.svg
  src/shared/components/challenge-detail/Specification/SideBar/ShareSocial.jsx
  src/shared/components/challenge-detail/Specification/SideBar/social_media.scss
Labels: Accessibility, Patched

#3167 Adding aria-label to num registrants for screen readers
  src/shared/components/challenge-listing/ChallengeCard/NumSubmissions/index.jsx
Labels: Accessibility, Code Review Passed

#3165 MSFT-22 New
  src/shared/components/TrackIcon/style.scss
Labels: Accessibility, Code Review Passed

#3158 MSFT-259
  __tests__/shared/components/ProfilePage/BadgesModal/__snapshots__/index.jsx.snap
  __tests__/shared/components/challenge-listing/Tooltips/__snapshots__/ProgressBarTooltip.jsx.snap
  __tests__/shared/components/challenge-listing/Tooltips/__snapshots__/TrackAbbreviationTooltip.jsx.snap
  __tests__/shared/components/challenge-listing/Tooltips/__snapshots__/UserAvatarTooltip.jsx.snap
  src/shared/components/Tooltip/index.jsx
  src/shared/components/challenge-detail/Specification/SideBar/index.jsx
Labels: Accessibility, Merged for QA

#3130 Changes for #3071
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Contentful, Merged for QA

#3129 Fix login button for screen reader
  __tests__/shared/components/TopcoderHeader/__snapshots__/Auth.jsx.snap
  src/shared/components/TopcoderHeader/Auth/index.jsx
Labels: Contentful, Merged for QA

#3061 Issue 2996 fix
  __tests__/shared/components/ProfilePage/Header/__snapshots__/index.jsx.snap
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  __tests__/shared/components/TopcoderHeader/mobile/__snapshots__/UserMenu.jsx.snap
  __tests__/shared/components/__snapshots__/Handle.jsx.snap
  src/shared/utils/tc.js
Labels: Accessibility, Merged for QA

#3168 Fix for Issue #2889 Challenge listing prize read out
  src/shared/components/challenge-listing/ChallengeCard/Prize/Tip/Bonus/index.jsx
  src/shared/components/challenge-listing/ChallengeCard/Prize/Tip/Prize/index.jsx
Labels: Accessibility, Merged for QA

#3157 MSFT-131
  src/shared/components/challenge-detail/Header/Prizes.jsx
Labels: Accessibility, Merged for QA

#3155 MSFT-102
  src/shared/components/challenge-listing/ChallengeCard/Prize/index.jsx
Labels: Accessibility, Code Review Passed

#3174 changes for 2799
  src/shared/components/SubmissionPage/Header/index.jsx
  src/shared/components/SubmissionPage/Header/styles.scss
Labels: Accessibility, Code Review Passed

#3132 Issue 3084 fix
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
  src/shared/components/TopcoderHeader/style.scss
Labels: Contentful, Merged for QA
