Repository topcoder-platform/community-app, pull requests merged in 2019-08, with the labels that each got.

#3177 MSFT-102 | Minor fix
  src/shared/components/challenge-listing/ChallengeCard/Prize/index.jsx
Labels: Accessibility, Merged for QA

#3183 Issue 2882 fix
  src/shared/components/challenge-detail/Header/DeadlinesPanel/Card/style.scss
  src/shared/components/challenge-detail/Header/DeadlinesPanel/style.scss
  src/shared/components/challenge-detail/Header/TabSelector/style.scss
  src/shared/components/challenge-detail/Header/style.scss
Labels: Accessibility, Merged for QA

#3179 Issue 2872 fix
  src/assets/images/ico-arrow-big-left.svg
  src/shared/components/challenge-detail/Header/index.jsx
Labels: Accessibility, Merged for QA

#3166 MSFT-125
  src/shared/components/challenge-detail/Registrants/index.jsx
Labels: Accessibility, Merged for QA

#3186 changes for #3185
  src/shared/components/SubmissionPage/Submit/index.jsx
  src/shared/components/SubmissionPage/Submit/styles.scss
Labels: Accessibility, Merged for QA

#3191 Fix the reading of Topcoder Logo
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Accessibility, Merged for QA

#3189 MSFT-86 | Update tooltip for review scorecard
  src/shared/components/challenge-detail/Specification/SideBar/index.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#3226 MSFT-131
  src/shared/components/challenge-detail/Header/Prizes.jsx
Labels: Accessibility, Code Review Passed

#3206 MSFT-187
  package.json
  src/shared/components/Terms/index.jsx
  src/shared/components/Terms/styles.scss
Labels: Accessibility, Merged for QA

#3202 MSFT-103
  src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx
Labels: Accessibility, Merged for QA

#3228 MSFT-103 | Minor Fixes
  src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx
Labels: Accessibility, Merged for QA

#3254 Fix for issues#3244
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeFilters.jsx.snap
  src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
Labels: Accessibility, Code Review Passed, Merged for QA

#3253 Change heading | Issue #3245
  __tests__/shared/components/__snapshots__/SortingSelectBar.jsx.snap
  src/shared/components/SortingSelectBar/index.jsx
  src/shared/components/challenge-listing/ChallengeCard/index.jsx
Labels: Accessibility, Merged for QA

#3252 Issue 3243 fix
  __tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeSearchBar.jsx.snap
  src/shared/components/challenge-listing/Filters/ChallengeSearchBar/index.jsx
Labels: Accessibility, Merged for QA

#3251 Issue 3247 fix
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Accessibility, Merged for QA

#3261 Issue 3246 fix
  __tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
  src/shared/components/TopcoderHeader/index.jsx
Labels: Accessibility, Merged for QA

#3258 Issue 3248 fix
  src/shared/components/challenge-detail/Header/index.jsx
Labels: Accessibility, Merged for QA
